
CREATE TABLE CONTA (
   ID INT PRIMARY KEY,
   NOME_CLIENTE VARCHAR(50), 
   SALDO FLOAT);
   

INSERT INTO CONTA (ID,NOME_CLIENTE, SALDO) VALUES (0,'FLAVIA', 200.00);
INSERT INTO CONTA (ID,NOME_CLIENTE, SALDO) VALUES (1, 'TIAGO', 100.00);
INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO) VALUES (2, 'MARIA', 300.00);


CREATE TABLE CONTA2 (
   ID INT PRIMARY KEY,
   NOME_CLIENTE VARCHAR(50), 
   SALDO FLOAT,
   VERSION DATE);
   

INSERT INTO CONTA2 (ID,NOME_CLIENTE, SALDO, VERSION) VALUES (0,'FLAVIA2', 200.00,NULL);
INSERT INTO CONTA2 (ID,NOME_CLIENTE, SALDO, VERSION) VALUES (1, 'TIAGO2', 100.00, NULL);
INSERT INTO CONTA2 (ID, NOME_CLIENTE, SALDO, VERSION) VALUES (2, 'MARIA2', 300.00, NULL);
